services:
  # grate:
  #   image: erikbra/grate:latest
  #   container_name: grate
  #   volumes:
  #     - ./Migrations/TH:/db
  #   environment:
  #     - DATABASE_TYPE=PostgreSQL
  #     - CREATE_DATABASE=true
  #     - TRANSACTION=true
  #     - APP_CONNSTRING=User ID=postgres;Password=Pass123!;Host=core;Port=5432;Database=core;Pooling=true
  #   networks:
  #     - grate

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Pass123!"
    networks:
      - grate

networks:
  grate:
    name: grate
    driver: bridge
    external: false